name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push Docker images
      run: |
        cd services/prediction
        docker build -t strasler/pdga-prediction:latest .
        docker push straslerj/pdga-prediction:latest
        
        cd ../scraper
        docker build -t strasler/pdga-scraper:latest .
        docker push straslerj/pdga-scraper:latest