name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy requirements
      run: |
        cp requirements.txt services/prediction
        cp requirements.txt services/scraper
        cp requirements.txt services/twitter


    - name: Create config
      run: |
        cd services/prediction
        echo "${{ secrets.CONFIG }}" > config.ini
        cd ../scraper
        echo "${{ secrets.CONFIG }}" > config.ini
        cd ../twitter
        echo "${{ secrets.CONFIG }}" > config.ini
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push Docker images
      run: |
        cd services/prediction
        docker build -t straslerj/pdga-prediction:latest .
        docker push straslerj/pdga-prediction:latest
        
        cd ../scraper
        docker build -t straslerj/pdga-scraper:latest .
        docker push straslerj/pdga-scraper:latest

        cd ../twitter
        docker build -t straslerj/pdga-twitter:latest .
        docker push straslerj/pdga-twitter:latest